### ISSUE TITLE
[Bug] Incorrect role assignment

### ISSUE THREAD

**Issue by MohitNSamagra** [CodeForGoodTech/C4GT#432]
**Problem:** Roles on discord are not being assigned by our bot
**Cause:** Deployment process is complex - Jenkis build with unsealing of vault. Unsealing the vault is unknown as of now.

**Comment by MohitNSamagra** [comment]
- to be picked alongside/after deployment - should be fixed with it

**Comment by MohitNSamagra** [comment]
@jaanbaaz to check with Kanav

**Comment by MohitNSamagra** [comment]
@jaanbaaz to debug with @KDwevedi

**Comment by KDwevedi** [comment]
### RCA
To deploy the discord bot, [this action](https://github.com/Code4GovTech/discord-bot/blob/main/.github/workflows/build-and-push.yml) is [run](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#push) on [commits to `main`](https://github.com/Code4GovTech/discord-bot/blob/070c07581c024a917c739c2a797d52bb44057a43/.github/workflows/build-and-push.yml#L4)  on the discord bot repo to build and push the docker image to [ghcr](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).

When jenkins deploy is triggered, it pulls this [image](https://docs.docker.com/get-started/docker-concepts/the-basics/what-is-an-image/) and deploys it as a docker container.

Unfortunately, the build-and-push action workflow was [failing](https://github.com/Code4GovTech/discord-bot/actions/runs/10834748273) because it was running the workflow file from `dev` branch which was broken.

If the image doesn't build, the image in the container repository doesn't update, therefore changes to the code don't get deployed.
Jenkins was working fine, it just wasn't deploying the updated image.

### The Fix
We [pushed a hotfix](https://github.com/Code4GovTech/discord-bot/pull/78) to the [.github/workflows](https://github.com/Code4GovTech/discord-bot/tree/main/.github/workflows) configuration file on the repo on the main branch that allows us to [trigger a image build for the main branch manually and selectively](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow).

This [ran successfully](https://github.com/Code4GovTech/discord-bot/actions/runs/10881839916) and updated the docker image, which in turn allows new prod changes to be deployed.

**Comment by MohitNSamagra** [comment]
- Delay added to code - to be checked with PT for reason and to be removed/reduced after @MohitNSamagra

**Comment by MohitNSamagra** [comment]
- to be checked @KDwevedi

**Comment by MohitNSamagra** [comment]
- Logs added

**Comment by MohitNSamagra** [comment]
- Being optimized by @karntrehan to lower role assignment time from 10 minutes+

**Comment by MohitNSamagra** [comment]
- to be closed today

**Comment by karntrehan** [comment]
Deployment undertaken. Bot not updated. Bot has been blocked by discord due to auto-spam id. Discord support has not come back. Need to figure a different approach. 

![Image](https://github.com/user-attachments/assets/dfc5ee26-37cf-43df-9179-ad016e994a9d)

**Comment by karntrehan** [comment]
Quarantine was not the issue. We had to run a db change on prod. It has been done now. 

Flow: 

1. User joins server
2. User accepts terms and conditions
3. User reaches `#authorize` channel
4. User clicks Register and fills the form
5. We update user's details in db (`contributors_discord`)
6. We check if user is already a verified contributor. If they are, flow ends here, else continues.
7. We should user a flow to authenticate via github
8. As soon as user clicks the button we start a loop to check if user has authenticated every 15 seconds. This is by checking `contributors_registration` table for user's discord id.
9. As soon as an entry is found, user is given verified contributor role. 
10. This loop waits for 5 mins and times out. Else a task runs every 60 mins to give all members of `contributors_registration` a verified contributor role.
